# Numpy

In [3]:
import numpy as np
import sys
s=range(1000)
print("Size Of Each Element Of List In Bytes:",sys.getsizeof(s))
print("Size of where list in bytes:",sys.getsizeof(s)*len(s))
D=np.arange(1000)
print("Size of each element of numpy array in bytes:",D.itemsize)
print("Size of whole numpy array in bytes:",D.size*D.itemsize)

Size Of Each Element Of List In Bytes: 48
Size of where list in bytes: 48000
Size of each element of numpy array in bytes: 4
Size of whole numpy array in bytes: 4000


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [9]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [10]:
import numpy as np
arr=np.array([[1,2,3,4,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [11]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [15]:
import numpy as np
arr=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [16]:
import numpy as np
arr=np.array([0,1,2,3,4,5])
print(arr[3])

3


In [18]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[3])
print(arr[4])
# print(arr[5])
print(arr[2]+arr[3])

4
5
7


In [40]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0][1])
print(arr[1][1])
print(arr[0][3])
print(arr[1][2])

2
7
4
8


In [27]:
import numpy as np
arr=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[0,1,2])
print(arr[1,0,1])

8
9
5
7


In [33]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-3])
print(arr[1,0:3])

8
[6 7 8]


In [39]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:3])
print(arr[1:])
print(arr[:-1])
print(arr[0:5:2])
print(arr[-3:-1])
print(arr[::-1])
print(arr[:-1:])
print(arr[:1:])
print(arr[:3:])


[2 3]
[2 3 4 5]
[1 2 3 4]
[1 3 5]
[3 4]
[5 4 3 2 1]
[1 2 3 4]
[1]
[1 2 3]


In [49]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,0:2,0:2])
print(arr[0:2,0:2,2])
print(arr[0:2,1,1])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[ 3  6]
 [ 9 12]]
[ 5 11]


In [54]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1.ndim)
print(arr1.shape)
print(arr2.ndim)
print(arr2.shape)
print(arr3.ndim)
print(arr3.shape)

1
(5,)
2
(2, 4)
3
(2, 2, 3)


In [57]:
import numpy as np
arr1=np.array([1,2,3,4,5],ndmin=5)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)


In [63]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(3,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]


In [64]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3,1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [70]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3).base
print(newarr)

[1 2 3 4 5 6]


In [69]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,-1)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [71]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3).base
newarr1=arr.reshape(2,3)
print(newarr)
print(newarr1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Iteration 

In [72]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for i in arr:
    print(i)

1
2
3
4
5
6


In [77]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [86]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(arr):
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [83]:
import numpy as np
arr=np.array([[1,2,3],[10,11,12]])
for i in np.nditer(arr[:,::2]):
        print(i)

1
3
10
12


In [85]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(arr[::-1,::3]):
        print(i)

1
2
3
7
8
9


# Built In Function

# Concatenate

In [88]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]
